// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCustomerParams creates a new GetCustomerParams object
// with the default values initialized.
func NewGetCustomerParams() *GetCustomerParams {
	var ()
	return &GetCustomerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCustomerParamsWithTimeout creates a new GetCustomerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCustomerParamsWithTimeout(timeout time.Duration) *GetCustomerParams {
	var ()
	return &GetCustomerParams{

		timeout: timeout,
	}
}

// NewGetCustomerParamsWithContext creates a new GetCustomerParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCustomerParamsWithContext(ctx context.Context) *GetCustomerParams {
	var ()
	return &GetCustomerParams{

		Context: ctx,
	}
}

// NewGetCustomerParamsWithHTTPClient creates a new GetCustomerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCustomerParamsWithHTTPClient(client *http.Client) *GetCustomerParams {
	var ()
	return &GetCustomerParams{
		HTTPClient: client,
	}
}

/*GetCustomerParams contains all the parameters to send to the API endpoint
for the get customer operation typically these are written to a http.Request
*/
type GetCustomerParams struct {

	/*CustomerTokenID
	  The TokenId of a customer.

	*/
	CustomerTokenID string
	/*ProfileID
	  The id of a profile containing user specific TMS configuration.

	*/
	ProfileID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get customer params
func (o *GetCustomerParams) WithTimeout(timeout time.Duration) *GetCustomerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get customer params
func (o *GetCustomerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get customer params
func (o *GetCustomerParams) WithContext(ctx context.Context) *GetCustomerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get customer params
func (o *GetCustomerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get customer params
func (o *GetCustomerParams) WithHTTPClient(client *http.Client) *GetCustomerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get customer params
func (o *GetCustomerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerTokenID adds the customerTokenID to the get customer params
func (o *GetCustomerParams) WithCustomerTokenID(customerTokenID string) *GetCustomerParams {
	o.SetCustomerTokenID(customerTokenID)
	return o
}

// SetCustomerTokenID adds the customerTokenId to the get customer params
func (o *GetCustomerParams) SetCustomerTokenID(customerTokenID string) {
	o.CustomerTokenID = customerTokenID
}

// WithProfileID adds the profileID to the get customer params
func (o *GetCustomerParams) WithProfileID(profileID *string) *GetCustomerParams {
	o.SetProfileID(profileID)
	return o
}

// SetProfileID adds the profileId to the get customer params
func (o *GetCustomerParams) SetProfileID(profileID *string) {
	o.ProfileID = profileID
}

// WriteToRequest writes these params to a swagger request
func (o *GetCustomerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param customerTokenId
	if err := r.SetPathParam("customerTokenId", o.CustomerTokenID); err != nil {
		return err
	}

	if o.ProfileID != nil {

		// header param profile-id
		if err := r.SetHeaderParam("profile-id", *o.ProfileID); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
