// Code generated by go-swagger; DO NOT EDIT.

package customer_shipping_address

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetCustomerShippingAddressesListReader is a Reader for the GetCustomerShippingAddressesList structure.
type GetCustomerShippingAddressesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCustomerShippingAddressesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCustomerShippingAddressesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetCustomerShippingAddressesListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetCustomerShippingAddressesListNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 410:
		result := NewGetCustomerShippingAddressesListGone()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetCustomerShippingAddressesListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetCustomerShippingAddressesListOK creates a GetCustomerShippingAddressesListOK with default headers values
func NewGetCustomerShippingAddressesListOK() *GetCustomerShippingAddressesListOK {
	return &GetCustomerShippingAddressesListOK{}
}

/*GetCustomerShippingAddressesListOK handles this case with default header values.

Returns all existing Shipping Addresses associated with the supplied token id.
*/
type GetCustomerShippingAddressesListOK struct {
	/*The total number of Shipping Addresses associated with the Customer.
	 */
	XTotalCount string
	/*A globally-unique ID associated with your request.
	 */
	UniqueTransactionID string
	/*The mandatory correlation id passed by upstream (calling) system.
	 */
	VcCorrelationID string

	Payload *GetCustomerShippingAddressesListOKBody
}

func (o *GetCustomerShippingAddressesListOK) Error() string {
	return fmt.Sprintf("[GET /tms/v2/customers/{customerTokenId}/shipping-addresses][%d] getCustomerShippingAddressesListOK  %+v", 200, o.Payload)
}

func (o *GetCustomerShippingAddressesListOK) GetPayload() *GetCustomerShippingAddressesListOKBody {
	return o.Payload
}

func (o *GetCustomerShippingAddressesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header X-Total-Count
	o.XTotalCount = response.GetHeader("X-Total-Count")

	// response header uniqueTransactionID
	o.UniqueTransactionID = response.GetHeader("uniqueTransactionID")

	// response header v-c-correlation-id
	o.VcCorrelationID = response.GetHeader("v-c-correlation-id")

	o.Payload = new(GetCustomerShippingAddressesListOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCustomerShippingAddressesListBadRequest creates a GetCustomerShippingAddressesListBadRequest with default headers values
func NewGetCustomerShippingAddressesListBadRequest() *GetCustomerShippingAddressesListBadRequest {
	return &GetCustomerShippingAddressesListBadRequest{}
}

/*GetCustomerShippingAddressesListBadRequest handles this case with default header values.

Bad Request: e.g. A required header value could be missing.
*/
type GetCustomerShippingAddressesListBadRequest struct {
	/*A globally unique id associated with your request.
	 */
	UniqueTransactionID string
	/*The mandatory correlation id passed by upstream (calling) system.
	 */
	VcCorrelationID string

	Payload *GetCustomerShippingAddressesListBadRequestBody
}

func (o *GetCustomerShippingAddressesListBadRequest) Error() string {
	return fmt.Sprintf("[GET /tms/v2/customers/{customerTokenId}/shipping-addresses][%d] getCustomerShippingAddressesListBadRequest  %+v", 400, o.Payload)
}

func (o *GetCustomerShippingAddressesListBadRequest) GetPayload() *GetCustomerShippingAddressesListBadRequestBody {
	return o.Payload
}

func (o *GetCustomerShippingAddressesListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header uniqueTransactionID
	o.UniqueTransactionID = response.GetHeader("uniqueTransactionID")

	// response header v-c-correlation-id
	o.VcCorrelationID = response.GetHeader("v-c-correlation-id")

	o.Payload = new(GetCustomerShippingAddressesListBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCustomerShippingAddressesListNotFound creates a GetCustomerShippingAddressesListNotFound with default headers values
func NewGetCustomerShippingAddressesListNotFound() *GetCustomerShippingAddressesListNotFound {
	return &GetCustomerShippingAddressesListNotFound{}
}

/*GetCustomerShippingAddressesListNotFound handles this case with default header values.

Token Not Found. The `tokenid` may not exist or was entered incorrectly.
*/
type GetCustomerShippingAddressesListNotFound struct {
	/*A globally unique ID associated with your request.
	 */
	UniqueTransactionID string
	/*The mandatory correlation id passed by upstream (calling) system.
	 */
	VcCorrelationID string

	Payload *GetCustomerShippingAddressesListNotFoundBody
}

func (o *GetCustomerShippingAddressesListNotFound) Error() string {
	return fmt.Sprintf("[GET /tms/v2/customers/{customerTokenId}/shipping-addresses][%d] getCustomerShippingAddressesListNotFound  %+v", 404, o.Payload)
}

func (o *GetCustomerShippingAddressesListNotFound) GetPayload() *GetCustomerShippingAddressesListNotFoundBody {
	return o.Payload
}

func (o *GetCustomerShippingAddressesListNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header uniqueTransactionID
	o.UniqueTransactionID = response.GetHeader("uniqueTransactionID")

	// response header v-c-correlation-id
	o.VcCorrelationID = response.GetHeader("v-c-correlation-id")

	o.Payload = new(GetCustomerShippingAddressesListNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCustomerShippingAddressesListGone creates a GetCustomerShippingAddressesListGone with default headers values
func NewGetCustomerShippingAddressesListGone() *GetCustomerShippingAddressesListGone {
	return &GetCustomerShippingAddressesListGone{}
}

/*GetCustomerShippingAddressesListGone handles this case with default header values.

Token Not Available. The token has been deleted.
*/
type GetCustomerShippingAddressesListGone struct {
	/*A globally unique ID associated with your request.
	 */
	UniqueTransactionID string
	/*The mandatory correlation id passed by upstream (calling) system.
	 */
	VcCorrelationID string

	Payload *GetCustomerShippingAddressesListGoneBody
}

func (o *GetCustomerShippingAddressesListGone) Error() string {
	return fmt.Sprintf("[GET /tms/v2/customers/{customerTokenId}/shipping-addresses][%d] getCustomerShippingAddressesListGone  %+v", 410, o.Payload)
}

func (o *GetCustomerShippingAddressesListGone) GetPayload() *GetCustomerShippingAddressesListGoneBody {
	return o.Payload
}

func (o *GetCustomerShippingAddressesListGone) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header uniqueTransactionID
	o.UniqueTransactionID = response.GetHeader("uniqueTransactionID")

	// response header v-c-correlation-id
	o.VcCorrelationID = response.GetHeader("v-c-correlation-id")

	o.Payload = new(GetCustomerShippingAddressesListGoneBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCustomerShippingAddressesListInternalServerError creates a GetCustomerShippingAddressesListInternalServerError with default headers values
func NewGetCustomerShippingAddressesListInternalServerError() *GetCustomerShippingAddressesListInternalServerError {
	return &GetCustomerShippingAddressesListInternalServerError{}
}

/*GetCustomerShippingAddressesListInternalServerError handles this case with default header values.

Unexpected error.
*/
type GetCustomerShippingAddressesListInternalServerError struct {
	/*A globally unique id associated with your request.
	 */
	UniqueTransactionID string
	/*The mandatory correlation id passed by upstream (calling) system.
	 */
	VcCorrelationID string

	Payload *GetCustomerShippingAddressesListInternalServerErrorBody
}

func (o *GetCustomerShippingAddressesListInternalServerError) Error() string {
	return fmt.Sprintf("[GET /tms/v2/customers/{customerTokenId}/shipping-addresses][%d] getCustomerShippingAddressesListInternalServerError  %+v", 500, o.Payload)
}

func (o *GetCustomerShippingAddressesListInternalServerError) GetPayload() *GetCustomerShippingAddressesListInternalServerErrorBody {
	return o.Payload
}

func (o *GetCustomerShippingAddressesListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header uniqueTransactionID
	o.UniqueTransactionID = response.GetHeader("uniqueTransactionID")

	// response header v-c-correlation-id
	o.VcCorrelationID = response.GetHeader("v-c-correlation-id")

	o.Payload = new(GetCustomerShippingAddressesListInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetCustomerShippingAddressesListBadRequestBody get customer shipping addresses list bad request body
swagger:model GetCustomerShippingAddressesListBadRequestBody
*/
type GetCustomerShippingAddressesListBadRequestBody struct {

	// errors
	// Read Only: true
	Errors []*GetCustomerShippingAddressesListBadRequestBodyErrorsItems0 `json:"errors"`
}

// Validate validates this get customer shipping addresses list bad request body
func (o *GetCustomerShippingAddressesListBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateErrors(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCustomerShippingAddressesListBadRequestBody) validateErrors(formats strfmt.Registry) error {

	if swag.IsZero(o.Errors) { // not required
		return nil
	}

	for i := 0; i < len(o.Errors); i++ {
		if swag.IsZero(o.Errors[i]) { // not required
			continue
		}

		if o.Errors[i] != nil {
			if err := o.Errors[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getCustomerShippingAddressesListBadRequest" + "." + "errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListBadRequestBody) UnmarshalBinary(b []byte) error {
	var res GetCustomerShippingAddressesListBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetCustomerShippingAddressesListBadRequestBodyErrorsItems0 get customer shipping addresses list bad request body errors items0
swagger:model GetCustomerShippingAddressesListBadRequestBodyErrorsItems0
*/
type GetCustomerShippingAddressesListBadRequestBodyErrorsItems0 struct {

	// details
	// Read Only: true
	Details []*GetCustomerShippingAddressesListBadRequestBodyErrorsItems0DetailsItems0 `json:"details"`

	// The detailed message related to the type stated above.
	// Read Only: true
	Message string `json:"message,omitempty"`

	// The type of error.
	// Read Only: true
	Type string `json:"type,omitempty"`
}

// Validate validates this get customer shipping addresses list bad request body errors items0
func (o *GetCustomerShippingAddressesListBadRequestBodyErrorsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCustomerShippingAddressesListBadRequestBodyErrorsItems0) validateDetails(formats strfmt.Registry) error {

	if swag.IsZero(o.Details) { // not required
		return nil
	}

	for i := 0; i < len(o.Details); i++ {
		if swag.IsZero(o.Details[i]) { // not required
			continue
		}

		if o.Details[i] != nil {
			if err := o.Details[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListBadRequestBodyErrorsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListBadRequestBodyErrorsItems0) UnmarshalBinary(b []byte) error {
	var res GetCustomerShippingAddressesListBadRequestBodyErrorsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetCustomerShippingAddressesListBadRequestBodyErrorsItems0DetailsItems0 get customer shipping addresses list bad request body errors items0 details items0
swagger:model GetCustomerShippingAddressesListBadRequestBodyErrorsItems0DetailsItems0
*/
type GetCustomerShippingAddressesListBadRequestBodyErrorsItems0DetailsItems0 struct {

	// The location of the field that caused the error.
	// Read Only: true
	Location string `json:"location,omitempty"`

	// The name of the field that caused the error.
	// Read Only: true
	Name string `json:"name,omitempty"`
}

// Validate validates this get customer shipping addresses list bad request body errors items0 details items0
func (o *GetCustomerShippingAddressesListBadRequestBodyErrorsItems0DetailsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListBadRequestBodyErrorsItems0DetailsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListBadRequestBodyErrorsItems0DetailsItems0) UnmarshalBinary(b []byte) error {
	var res GetCustomerShippingAddressesListBadRequestBodyErrorsItems0DetailsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetCustomerShippingAddressesListGoneBody get customer shipping addresses list gone body
swagger:model GetCustomerShippingAddressesListGoneBody
*/
type GetCustomerShippingAddressesListGoneBody struct {

	// errors
	// Read Only: true
	Errors []*GetCustomerShippingAddressesListGoneBodyErrorsItems0 `json:"errors"`
}

// Validate validates this get customer shipping addresses list gone body
func (o *GetCustomerShippingAddressesListGoneBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateErrors(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCustomerShippingAddressesListGoneBody) validateErrors(formats strfmt.Registry) error {

	if swag.IsZero(o.Errors) { // not required
		return nil
	}

	for i := 0; i < len(o.Errors); i++ {
		if swag.IsZero(o.Errors[i]) { // not required
			continue
		}

		if o.Errors[i] != nil {
			if err := o.Errors[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getCustomerShippingAddressesListGone" + "." + "errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListGoneBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListGoneBody) UnmarshalBinary(b []byte) error {
	var res GetCustomerShippingAddressesListGoneBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetCustomerShippingAddressesListGoneBodyErrorsItems0 get customer shipping addresses list gone body errors items0
swagger:model GetCustomerShippingAddressesListGoneBodyErrorsItems0
*/
type GetCustomerShippingAddressesListGoneBodyErrorsItems0 struct {

	// details
	// Read Only: true
	Details []*GetCustomerShippingAddressesListGoneBodyErrorsItems0DetailsItems0 `json:"details"`

	// The detailed message related to the type stated above.
	// Read Only: true
	Message string `json:"message,omitempty"`

	// The type of error.
	// Read Only: true
	Type string `json:"type,omitempty"`
}

// Validate validates this get customer shipping addresses list gone body errors items0
func (o *GetCustomerShippingAddressesListGoneBodyErrorsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCustomerShippingAddressesListGoneBodyErrorsItems0) validateDetails(formats strfmt.Registry) error {

	if swag.IsZero(o.Details) { // not required
		return nil
	}

	for i := 0; i < len(o.Details); i++ {
		if swag.IsZero(o.Details[i]) { // not required
			continue
		}

		if o.Details[i] != nil {
			if err := o.Details[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListGoneBodyErrorsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListGoneBodyErrorsItems0) UnmarshalBinary(b []byte) error {
	var res GetCustomerShippingAddressesListGoneBodyErrorsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetCustomerShippingAddressesListGoneBodyErrorsItems0DetailsItems0 get customer shipping addresses list gone body errors items0 details items0
swagger:model GetCustomerShippingAddressesListGoneBodyErrorsItems0DetailsItems0
*/
type GetCustomerShippingAddressesListGoneBodyErrorsItems0DetailsItems0 struct {

	// The location of the field that caused the error.
	// Read Only: true
	Location string `json:"location,omitempty"`

	// The name of the field that caused the error.
	// Read Only: true
	Name string `json:"name,omitempty"`
}

// Validate validates this get customer shipping addresses list gone body errors items0 details items0
func (o *GetCustomerShippingAddressesListGoneBodyErrorsItems0DetailsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListGoneBodyErrorsItems0DetailsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListGoneBodyErrorsItems0DetailsItems0) UnmarshalBinary(b []byte) error {
	var res GetCustomerShippingAddressesListGoneBodyErrorsItems0DetailsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetCustomerShippingAddressesListInternalServerErrorBody get customer shipping addresses list internal server error body
swagger:model GetCustomerShippingAddressesListInternalServerErrorBody
*/
type GetCustomerShippingAddressesListInternalServerErrorBody struct {

	// errors
	// Read Only: true
	Errors []*GetCustomerShippingAddressesListInternalServerErrorBodyErrorsItems0 `json:"errors"`
}

// Validate validates this get customer shipping addresses list internal server error body
func (o *GetCustomerShippingAddressesListInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateErrors(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCustomerShippingAddressesListInternalServerErrorBody) validateErrors(formats strfmt.Registry) error {

	if swag.IsZero(o.Errors) { // not required
		return nil
	}

	for i := 0; i < len(o.Errors); i++ {
		if swag.IsZero(o.Errors[i]) { // not required
			continue
		}

		if o.Errors[i] != nil {
			if err := o.Errors[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getCustomerShippingAddressesListInternalServerError" + "." + "errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res GetCustomerShippingAddressesListInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetCustomerShippingAddressesListInternalServerErrorBodyErrorsItems0 get customer shipping addresses list internal server error body errors items0
swagger:model GetCustomerShippingAddressesListInternalServerErrorBodyErrorsItems0
*/
type GetCustomerShippingAddressesListInternalServerErrorBodyErrorsItems0 struct {

	// details
	// Read Only: true
	Details []*GetCustomerShippingAddressesListInternalServerErrorBodyErrorsItems0DetailsItems0 `json:"details"`

	// The detailed message related to the type stated above.
	// Read Only: true
	Message string `json:"message,omitempty"`

	// The type of error.
	// Read Only: true
	Type string `json:"type,omitempty"`
}

// Validate validates this get customer shipping addresses list internal server error body errors items0
func (o *GetCustomerShippingAddressesListInternalServerErrorBodyErrorsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCustomerShippingAddressesListInternalServerErrorBodyErrorsItems0) validateDetails(formats strfmt.Registry) error {

	if swag.IsZero(o.Details) { // not required
		return nil
	}

	for i := 0; i < len(o.Details); i++ {
		if swag.IsZero(o.Details[i]) { // not required
			continue
		}

		if o.Details[i] != nil {
			if err := o.Details[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListInternalServerErrorBodyErrorsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListInternalServerErrorBodyErrorsItems0) UnmarshalBinary(b []byte) error {
	var res GetCustomerShippingAddressesListInternalServerErrorBodyErrorsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetCustomerShippingAddressesListInternalServerErrorBodyErrorsItems0DetailsItems0 get customer shipping addresses list internal server error body errors items0 details items0
swagger:model GetCustomerShippingAddressesListInternalServerErrorBodyErrorsItems0DetailsItems0
*/
type GetCustomerShippingAddressesListInternalServerErrorBodyErrorsItems0DetailsItems0 struct {

	// The location of the field that caused the error.
	// Read Only: true
	Location string `json:"location,omitempty"`

	// The name of the field that caused the error.
	// Read Only: true
	Name string `json:"name,omitempty"`
}

// Validate validates this get customer shipping addresses list internal server error body errors items0 details items0
func (o *GetCustomerShippingAddressesListInternalServerErrorBodyErrorsItems0DetailsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListInternalServerErrorBodyErrorsItems0DetailsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListInternalServerErrorBodyErrorsItems0DetailsItems0) UnmarshalBinary(b []byte) error {
	var res GetCustomerShippingAddressesListInternalServerErrorBodyErrorsItems0DetailsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetCustomerShippingAddressesListNotFoundBody get customer shipping addresses list not found body
swagger:model GetCustomerShippingAddressesListNotFoundBody
*/
type GetCustomerShippingAddressesListNotFoundBody struct {

	// errors
	// Read Only: true
	Errors []*GetCustomerShippingAddressesListNotFoundBodyErrorsItems0 `json:"errors"`
}

// Validate validates this get customer shipping addresses list not found body
func (o *GetCustomerShippingAddressesListNotFoundBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateErrors(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCustomerShippingAddressesListNotFoundBody) validateErrors(formats strfmt.Registry) error {

	if swag.IsZero(o.Errors) { // not required
		return nil
	}

	for i := 0; i < len(o.Errors); i++ {
		if swag.IsZero(o.Errors[i]) { // not required
			continue
		}

		if o.Errors[i] != nil {
			if err := o.Errors[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getCustomerShippingAddressesListNotFound" + "." + "errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListNotFoundBody) UnmarshalBinary(b []byte) error {
	var res GetCustomerShippingAddressesListNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetCustomerShippingAddressesListNotFoundBodyErrorsItems0 get customer shipping addresses list not found body errors items0
swagger:model GetCustomerShippingAddressesListNotFoundBodyErrorsItems0
*/
type GetCustomerShippingAddressesListNotFoundBodyErrorsItems0 struct {

	// details
	// Read Only: true
	Details []*GetCustomerShippingAddressesListNotFoundBodyErrorsItems0DetailsItems0 `json:"details"`

	// The detailed message related to the type stated above.
	// Read Only: true
	Message string `json:"message,omitempty"`

	// The type of error.
	// Read Only: true
	Type string `json:"type,omitempty"`
}

// Validate validates this get customer shipping addresses list not found body errors items0
func (o *GetCustomerShippingAddressesListNotFoundBodyErrorsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCustomerShippingAddressesListNotFoundBodyErrorsItems0) validateDetails(formats strfmt.Registry) error {

	if swag.IsZero(o.Details) { // not required
		return nil
	}

	for i := 0; i < len(o.Details); i++ {
		if swag.IsZero(o.Details[i]) { // not required
			continue
		}

		if o.Details[i] != nil {
			if err := o.Details[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListNotFoundBodyErrorsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListNotFoundBodyErrorsItems0) UnmarshalBinary(b []byte) error {
	var res GetCustomerShippingAddressesListNotFoundBodyErrorsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetCustomerShippingAddressesListNotFoundBodyErrorsItems0DetailsItems0 get customer shipping addresses list not found body errors items0 details items0
swagger:model GetCustomerShippingAddressesListNotFoundBodyErrorsItems0DetailsItems0
*/
type GetCustomerShippingAddressesListNotFoundBodyErrorsItems0DetailsItems0 struct {

	// The location of the field that caused the error.
	// Read Only: true
	Location string `json:"location,omitempty"`

	// The name of the field that caused the error.
	// Read Only: true
	Name string `json:"name,omitempty"`
}

// Validate validates this get customer shipping addresses list not found body errors items0 details items0
func (o *GetCustomerShippingAddressesListNotFoundBodyErrorsItems0DetailsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListNotFoundBodyErrorsItems0DetailsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListNotFoundBodyErrorsItems0DetailsItems0) UnmarshalBinary(b []byte) error {
	var res GetCustomerShippingAddressesListNotFoundBodyErrorsItems0DetailsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetCustomerShippingAddressesListOKBody ShippingAddressListForCustomer
//
// A paginated container of Shipping Addresses.
//
swagger:model GetCustomerShippingAddressesListOKBody
*/
type GetCustomerShippingAddressesListOKBody struct {

	// embedded
	Embedded *GetCustomerShippingAddressesListOKBodyEmbedded `json:"_embedded,omitempty"`

	// links
	Links *GetCustomerShippingAddressesListOKBodyLinks `json:"_links,omitempty"`

	// The number of Shipping Addresses returned in the array.
	// Read Only: true
	Count int64 `json:"count,omitempty"`

	// The limit parameter supplied in the request.
	// Read Only: true
	Limit int64 `json:"limit,omitempty"`

	// The offset parameter supplied in the request.
	// Read Only: true
	Offset int64 `json:"offset,omitempty"`

	// The total number of Shipping Addresses associated with the Customer.
	// Read Only: true
	Total int64 `json:"total,omitempty"`
}

// Validate validates this get customer shipping addresses list o k body
func (o *GetCustomerShippingAddressesListOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEmbedded(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCustomerShippingAddressesListOKBody) validateEmbedded(formats strfmt.Registry) error {

	if swag.IsZero(o.Embedded) { // not required
		return nil
	}

	if o.Embedded != nil {
		if err := o.Embedded.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getCustomerShippingAddressesListOK" + "." + "_embedded")
			}
			return err
		}
	}

	return nil
}

func (o *GetCustomerShippingAddressesListOKBody) validateLinks(formats strfmt.Registry) error {

	if swag.IsZero(o.Links) { // not required
		return nil
	}

	if o.Links != nil {
		if err := o.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getCustomerShippingAddressesListOK" + "." + "_links")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBody) UnmarshalBinary(b []byte) error {
	var res GetCustomerShippingAddressesListOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetCustomerShippingAddressesListOKBodyEmbedded Shipping Address Resources.
//
swagger:model GetCustomerShippingAddressesListOKBodyEmbedded
*/
type GetCustomerShippingAddressesListOKBodyEmbedded struct {

	// shipping addresses
	// Read Only: true
	ShippingAddresses []*GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0 `json:"shippingAddresses"`
}

// Validate validates this get customer shipping addresses list o k body embedded
func (o *GetCustomerShippingAddressesListOKBodyEmbedded) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateShippingAddresses(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCustomerShippingAddressesListOKBodyEmbedded) validateShippingAddresses(formats strfmt.Registry) error {

	if swag.IsZero(o.ShippingAddresses) { // not required
		return nil
	}

	for i := 0; i < len(o.ShippingAddresses); i++ {
		if swag.IsZero(o.ShippingAddresses[i]) { // not required
			continue
		}

		if o.ShippingAddresses[i] != nil {
			if err := o.ShippingAddresses[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getCustomerShippingAddressesListOK" + "." + "_embedded" + "." + "shippingAddresses" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBodyEmbedded) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBodyEmbedded) UnmarshalBinary(b []byte) error {
	var res GetCustomerShippingAddressesListOKBodyEmbedded
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0 get customer shipping addresses list o k body embedded shipping addresses items0
swagger:model GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0
*/
type GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0 struct {

	// links
	Links *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0Links `json:"_links,omitempty"`

	// The id of the Shipping Address Token.
	// Max Length: 32
	// Min Length: 1
	ID string `json:"id,omitempty"`

	// metadata
	Metadata *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0Metadata `json:"metadata,omitempty"`

	// ship to
	ShipTo *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0ShipTo `json:"shipTo,omitempty"`
}

// Validate validates this get customer shipping addresses list o k body embedded shipping addresses items0
func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateMetadata(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateShipTo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0) validateLinks(formats strfmt.Registry) error {

	if swag.IsZero(o.Links) { // not required
		return nil
	}

	if o.Links != nil {
		if err := o.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("_links")
			}
			return err
		}
	}

	return nil
}

func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0) validateID(formats strfmt.Registry) error {

	if swag.IsZero(o.ID) { // not required
		return nil
	}

	if err := validate.MinLength("id", "body", string(o.ID), 1); err != nil {
		return err
	}

	if err := validate.MaxLength("id", "body", string(o.ID), 32); err != nil {
		return err
	}

	return nil
}

func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0) validateMetadata(formats strfmt.Registry) error {

	if swag.IsZero(o.Metadata) { // not required
		return nil
	}

	if o.Metadata != nil {
		if err := o.Metadata.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metadata")
			}
			return err
		}
	}

	return nil
}

func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0) validateShipTo(formats strfmt.Registry) error {

	if swag.IsZero(o.ShipTo) { // not required
		return nil
	}

	if o.ShipTo != nil {
		if err := o.ShipTo.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("shipTo")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0) UnmarshalBinary(b []byte) error {
	var res GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0Links get customer shipping addresses list o k body embedded shipping addresses items0 links
swagger:model GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0Links
*/
type GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0Links struct {

	// customer
	Customer *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0LinksCustomer `json:"customer,omitempty"`

	// self
	Self *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0LinksSelf `json:"self,omitempty"`
}

// Validate validates this get customer shipping addresses list o k body embedded shipping addresses items0 links
func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0Links) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCustomer(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateSelf(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0Links) validateCustomer(formats strfmt.Registry) error {

	if swag.IsZero(o.Customer) { // not required
		return nil
	}

	if o.Customer != nil {
		if err := o.Customer.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("_links" + "." + "customer")
			}
			return err
		}
	}

	return nil
}

func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0Links) validateSelf(formats strfmt.Registry) error {

	if swag.IsZero(o.Self) { // not required
		return nil
	}

	if o.Self != nil {
		if err := o.Self.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("_links" + "." + "self")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0Links) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0Links) UnmarshalBinary(b []byte) error {
	var res GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0Links
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0LinksCustomer get customer shipping addresses list o k body embedded shipping addresses items0 links customer
swagger:model GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0LinksCustomer
*/
type GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0LinksCustomer struct {

	// Link to the Customer
	//
	// Read Only: true
	Href string `json:"href,omitempty"`
}

// Validate validates this get customer shipping addresses list o k body embedded shipping addresses items0 links customer
func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0LinksCustomer) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0LinksCustomer) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0LinksCustomer) UnmarshalBinary(b []byte) error {
	var res GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0LinksCustomer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0LinksSelf get customer shipping addresses list o k body embedded shipping addresses items0 links self
swagger:model GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0LinksSelf
*/
type GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0LinksSelf struct {

	// Link to the Customers Shipping Address
	//
	// Read Only: true
	Href string `json:"href,omitempty"`
}

// Validate validates this get customer shipping addresses list o k body embedded shipping addresses items0 links self
func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0LinksSelf) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0LinksSelf) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0LinksSelf) UnmarshalBinary(b []byte) error {
	var res GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0LinksSelf
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0Metadata get customer shipping addresses list o k body embedded shipping addresses items0 metadata
swagger:model GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0Metadata
*/
type GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0Metadata struct {

	// The creator of the Shipping Address token.
	// Read Only: true
	Creator string `json:"creator,omitempty"`
}

// Validate validates this get customer shipping addresses list o k body embedded shipping addresses items0 metadata
func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0Metadata) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0Metadata) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0Metadata) UnmarshalBinary(b []byte) error {
	var res GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0Metadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0ShipTo get customer shipping addresses list o k body embedded shipping addresses items0 ship to
swagger:model GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0ShipTo
*/
type GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0ShipTo struct {

	// First line of the shipping address.
	//
	// Max Length: 60
	Address1 string `json:"address1,omitempty"`

	// Second line of the shipping address.
	//
	// Max Length: 60
	Address2 string `json:"address2,omitempty"`

	// State or province of the shipping address. Use 2 character the State,
	// Province, and Territory Codes for the United States and Canada.
	//
	// Max Length: 20
	AdministrativeArea string `json:"administrativeArea,omitempty"`

	// Company associated with the shipping address.
	//
	// Max Length: 60
	Company string `json:"company,omitempty"`

	// Country of the shipping address. Use the two-character ISO Standard Country Codes.
	//
	// Max Length: 2
	Country string `json:"country,omitempty"`

	// Email associated with the shipping address.
	//
	// Max Length: 320
	Email string `json:"email,omitempty"`

	// First name of the recipient.
	//
	// Max Length: 60
	FirstName string `json:"firstName,omitempty"`

	// Last name of the recipient.
	//
	// Max Length: 60
	LastName string `json:"lastName,omitempty"`

	// City of the shipping address.
	//
	// Max Length: 50
	Locality string `json:"locality,omitempty"`

	// Phone number associated with the shipping address.
	//
	// Max Length: 15
	PhoneNumber string `json:"phoneNumber,omitempty"`

	// Postal code for the shipping address. The postal code must consist of 5 to 9 digits.
	//
	// When the billing country is the U.S., the 9-digit postal code must follow this format:
	// [5 digits][dash][4 digits]
	//
	// Example 12345-6789
	//
	// When the billing country is Canada, the 6-digit postal code must follow this format:
	// [alpha][numeric][alpha][space][numeric][alpha][numeric]
	//
	// Example A1B 2C3
	//
	// **American Express Direct**\
	// Before sending the postal code to the processor, CyberSource removes all nonalphanumeric characters and, if the
	// remaining value is longer than nine characters, truncates the value starting from the right side.
	//
	// Max Length: 10
	PostalCode string `json:"postalCode,omitempty"`
}

// Validate validates this get customer shipping addresses list o k body embedded shipping addresses items0 ship to
func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0ShipTo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAddress1(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateAddress2(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateAdministrativeArea(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateCompany(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateCountry(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateFirstName(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLastName(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLocality(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePhoneNumber(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePostalCode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0ShipTo) validateAddress1(formats strfmt.Registry) error {

	if swag.IsZero(o.Address1) { // not required
		return nil
	}

	if err := validate.MaxLength("shipTo"+"."+"address1", "body", string(o.Address1), 60); err != nil {
		return err
	}

	return nil
}

func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0ShipTo) validateAddress2(formats strfmt.Registry) error {

	if swag.IsZero(o.Address2) { // not required
		return nil
	}

	if err := validate.MaxLength("shipTo"+"."+"address2", "body", string(o.Address2), 60); err != nil {
		return err
	}

	return nil
}

func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0ShipTo) validateAdministrativeArea(formats strfmt.Registry) error {

	if swag.IsZero(o.AdministrativeArea) { // not required
		return nil
	}

	if err := validate.MaxLength("shipTo"+"."+"administrativeArea", "body", string(o.AdministrativeArea), 20); err != nil {
		return err
	}

	return nil
}

func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0ShipTo) validateCompany(formats strfmt.Registry) error {

	if swag.IsZero(o.Company) { // not required
		return nil
	}

	if err := validate.MaxLength("shipTo"+"."+"company", "body", string(o.Company), 60); err != nil {
		return err
	}

	return nil
}

func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0ShipTo) validateCountry(formats strfmt.Registry) error {

	if swag.IsZero(o.Country) { // not required
		return nil
	}

	if err := validate.MaxLength("shipTo"+"."+"country", "body", string(o.Country), 2); err != nil {
		return err
	}

	return nil
}

func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0ShipTo) validateEmail(formats strfmt.Registry) error {

	if swag.IsZero(o.Email) { // not required
		return nil
	}

	if err := validate.MaxLength("shipTo"+"."+"email", "body", string(o.Email), 320); err != nil {
		return err
	}

	return nil
}

func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0ShipTo) validateFirstName(formats strfmt.Registry) error {

	if swag.IsZero(o.FirstName) { // not required
		return nil
	}

	if err := validate.MaxLength("shipTo"+"."+"firstName", "body", string(o.FirstName), 60); err != nil {
		return err
	}

	return nil
}

func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0ShipTo) validateLastName(formats strfmt.Registry) error {

	if swag.IsZero(o.LastName) { // not required
		return nil
	}

	if err := validate.MaxLength("shipTo"+"."+"lastName", "body", string(o.LastName), 60); err != nil {
		return err
	}

	return nil
}

func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0ShipTo) validateLocality(formats strfmt.Registry) error {

	if swag.IsZero(o.Locality) { // not required
		return nil
	}

	if err := validate.MaxLength("shipTo"+"."+"locality", "body", string(o.Locality), 50); err != nil {
		return err
	}

	return nil
}

func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0ShipTo) validatePhoneNumber(formats strfmt.Registry) error {

	if swag.IsZero(o.PhoneNumber) { // not required
		return nil
	}

	if err := validate.MaxLength("shipTo"+"."+"phoneNumber", "body", string(o.PhoneNumber), 15); err != nil {
		return err
	}

	return nil
}

func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0ShipTo) validatePostalCode(formats strfmt.Registry) error {

	if swag.IsZero(o.PostalCode) { // not required
		return nil
	}

	if err := validate.MaxLength("shipTo"+"."+"postalCode", "body", string(o.PostalCode), 10); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0ShipTo) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0ShipTo) UnmarshalBinary(b []byte) error {
	var res GetCustomerShippingAddressesListOKBodyEmbeddedShippingAddressesItems0ShipTo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetCustomerShippingAddressesListOKBodyLinks get customer shipping addresses list o k body links
swagger:model GetCustomerShippingAddressesListOKBodyLinks
*/
type GetCustomerShippingAddressesListOKBodyLinks struct {

	// first
	First *GetCustomerShippingAddressesListOKBodyLinksFirst `json:"first,omitempty"`

	// last
	Last *GetCustomerShippingAddressesListOKBodyLinksLast `json:"last,omitempty"`

	// next
	Next *GetCustomerShippingAddressesListOKBodyLinksNext `json:"next,omitempty"`

	// prev
	Prev *GetCustomerShippingAddressesListOKBodyLinksPrev `json:"prev,omitempty"`

	// self
	Self *GetCustomerShippingAddressesListOKBodyLinksSelf `json:"self,omitempty"`
}

// Validate validates this get customer shipping addresses list o k body links
func (o *GetCustomerShippingAddressesListOKBodyLinks) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateFirst(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLast(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateNext(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePrev(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateSelf(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCustomerShippingAddressesListOKBodyLinks) validateFirst(formats strfmt.Registry) error {

	if swag.IsZero(o.First) { // not required
		return nil
	}

	if o.First != nil {
		if err := o.First.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getCustomerShippingAddressesListOK" + "." + "_links" + "." + "first")
			}
			return err
		}
	}

	return nil
}

func (o *GetCustomerShippingAddressesListOKBodyLinks) validateLast(formats strfmt.Registry) error {

	if swag.IsZero(o.Last) { // not required
		return nil
	}

	if o.Last != nil {
		if err := o.Last.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getCustomerShippingAddressesListOK" + "." + "_links" + "." + "last")
			}
			return err
		}
	}

	return nil
}

func (o *GetCustomerShippingAddressesListOKBodyLinks) validateNext(formats strfmt.Registry) error {

	if swag.IsZero(o.Next) { // not required
		return nil
	}

	if o.Next != nil {
		if err := o.Next.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getCustomerShippingAddressesListOK" + "." + "_links" + "." + "next")
			}
			return err
		}
	}

	return nil
}

func (o *GetCustomerShippingAddressesListOKBodyLinks) validatePrev(formats strfmt.Registry) error {

	if swag.IsZero(o.Prev) { // not required
		return nil
	}

	if o.Prev != nil {
		if err := o.Prev.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getCustomerShippingAddressesListOK" + "." + "_links" + "." + "prev")
			}
			return err
		}
	}

	return nil
}

func (o *GetCustomerShippingAddressesListOKBodyLinks) validateSelf(formats strfmt.Registry) error {

	if swag.IsZero(o.Self) { // not required
		return nil
	}

	if o.Self != nil {
		if err := o.Self.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getCustomerShippingAddressesListOK" + "." + "_links" + "." + "self")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBodyLinks) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBodyLinks) UnmarshalBinary(b []byte) error {
	var res GetCustomerShippingAddressesListOKBodyLinks
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetCustomerShippingAddressesListOKBodyLinksFirst get customer shipping addresses list o k body links first
swagger:model GetCustomerShippingAddressesListOKBodyLinksFirst
*/
type GetCustomerShippingAddressesListOKBodyLinksFirst struct {

	// Link to the first page.
	//
	// Read Only: true
	Href string `json:"href,omitempty"`
}

// Validate validates this get customer shipping addresses list o k body links first
func (o *GetCustomerShippingAddressesListOKBodyLinksFirst) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBodyLinksFirst) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBodyLinksFirst) UnmarshalBinary(b []byte) error {
	var res GetCustomerShippingAddressesListOKBodyLinksFirst
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetCustomerShippingAddressesListOKBodyLinksLast get customer shipping addresses list o k body links last
swagger:model GetCustomerShippingAddressesListOKBodyLinksLast
*/
type GetCustomerShippingAddressesListOKBodyLinksLast struct {

	// Link to the last page.
	//
	// Read Only: true
	Href string `json:"href,omitempty"`
}

// Validate validates this get customer shipping addresses list o k body links last
func (o *GetCustomerShippingAddressesListOKBodyLinksLast) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBodyLinksLast) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBodyLinksLast) UnmarshalBinary(b []byte) error {
	var res GetCustomerShippingAddressesListOKBodyLinksLast
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetCustomerShippingAddressesListOKBodyLinksNext get customer shipping addresses list o k body links next
swagger:model GetCustomerShippingAddressesListOKBodyLinksNext
*/
type GetCustomerShippingAddressesListOKBodyLinksNext struct {

	// Link to the next page.
	//
	// Read Only: true
	Href string `json:"href,omitempty"`
}

// Validate validates this get customer shipping addresses list o k body links next
func (o *GetCustomerShippingAddressesListOKBodyLinksNext) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBodyLinksNext) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBodyLinksNext) UnmarshalBinary(b []byte) error {
	var res GetCustomerShippingAddressesListOKBodyLinksNext
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetCustomerShippingAddressesListOKBodyLinksPrev get customer shipping addresses list o k body links prev
swagger:model GetCustomerShippingAddressesListOKBodyLinksPrev
*/
type GetCustomerShippingAddressesListOKBodyLinksPrev struct {

	// Link to the previous page.
	//
	// Read Only: true
	Href string `json:"href,omitempty"`
}

// Validate validates this get customer shipping addresses list o k body links prev
func (o *GetCustomerShippingAddressesListOKBodyLinksPrev) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBodyLinksPrev) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBodyLinksPrev) UnmarshalBinary(b []byte) error {
	var res GetCustomerShippingAddressesListOKBodyLinksPrev
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetCustomerShippingAddressesListOKBodyLinksSelf get customer shipping addresses list o k body links self
swagger:model GetCustomerShippingAddressesListOKBodyLinksSelf
*/
type GetCustomerShippingAddressesListOKBodyLinksSelf struct {

	// Link to the current page.
	//
	// Read Only: true
	Href string `json:"href,omitempty"`
}

// Validate validates this get customer shipping addresses list o k body links self
func (o *GetCustomerShippingAddressesListOKBodyLinksSelf) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBodyLinksSelf) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCustomerShippingAddressesListOKBodyLinksSelf) UnmarshalBinary(b []byte) error {
	var res GetCustomerShippingAddressesListOKBodyLinksSelf
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
