// Code generated by go-swagger; DO NOT EDIT.

package invoices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPerformCancelActionParams creates a new PerformCancelActionParams object
// with the default values initialized.
func NewPerformCancelActionParams() *PerformCancelActionParams {
	var ()
	return &PerformCancelActionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPerformCancelActionParamsWithTimeout creates a new PerformCancelActionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPerformCancelActionParamsWithTimeout(timeout time.Duration) *PerformCancelActionParams {
	var ()
	return &PerformCancelActionParams{

		timeout: timeout,
	}
}

// NewPerformCancelActionParamsWithContext creates a new PerformCancelActionParams object
// with the default values initialized, and the ability to set a context for a request
func NewPerformCancelActionParamsWithContext(ctx context.Context) *PerformCancelActionParams {
	var ()
	return &PerformCancelActionParams{

		Context: ctx,
	}
}

// NewPerformCancelActionParamsWithHTTPClient creates a new PerformCancelActionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPerformCancelActionParamsWithHTTPClient(client *http.Client) *PerformCancelActionParams {
	var ()
	return &PerformCancelActionParams{
		HTTPClient: client,
	}
}

/*PerformCancelActionParams contains all the parameters to send to the API endpoint
for the perform cancel action operation typically these are written to a http.Request
*/
type PerformCancelActionParams struct {

	/*ID
	  The invoice number.

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the perform cancel action params
func (o *PerformCancelActionParams) WithTimeout(timeout time.Duration) *PerformCancelActionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the perform cancel action params
func (o *PerformCancelActionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the perform cancel action params
func (o *PerformCancelActionParams) WithContext(ctx context.Context) *PerformCancelActionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the perform cancel action params
func (o *PerformCancelActionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the perform cancel action params
func (o *PerformCancelActionParams) WithHTTPClient(client *http.Client) *PerformCancelActionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the perform cancel action params
func (o *PerformCancelActionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the perform cancel action params
func (o *PerformCancelActionParams) WithID(id string) *PerformCancelActionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the perform cancel action params
func (o *PerformCancelActionParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PerformCancelActionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
