// Code generated by go-swagger; DO NOT EDIT.

package payments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewIncrementAuthParams creates a new IncrementAuthParams object
// with the default values initialized.
func NewIncrementAuthParams() *IncrementAuthParams {
	var ()
	return &IncrementAuthParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIncrementAuthParamsWithTimeout creates a new IncrementAuthParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIncrementAuthParamsWithTimeout(timeout time.Duration) *IncrementAuthParams {
	var ()
	return &IncrementAuthParams{

		timeout: timeout,
	}
}

// NewIncrementAuthParamsWithContext creates a new IncrementAuthParams object
// with the default values initialized, and the ability to set a context for a request
func NewIncrementAuthParamsWithContext(ctx context.Context) *IncrementAuthParams {
	var ()
	return &IncrementAuthParams{

		Context: ctx,
	}
}

// NewIncrementAuthParamsWithHTTPClient creates a new IncrementAuthParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIncrementAuthParamsWithHTTPClient(client *http.Client) *IncrementAuthParams {
	var ()
	return &IncrementAuthParams{
		HTTPClient: client,
	}
}

/*IncrementAuthParams contains all the parameters to send to the API endpoint
for the increment auth operation typically these are written to a http.Request
*/
type IncrementAuthParams struct {

	/*ID
	  The ID returned from the original authorization request.

	*/
	ID string
	/*IncrementAuthRequest*/
	IncrementAuthRequest IncrementAuthBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the increment auth params
func (o *IncrementAuthParams) WithTimeout(timeout time.Duration) *IncrementAuthParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the increment auth params
func (o *IncrementAuthParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the increment auth params
func (o *IncrementAuthParams) WithContext(ctx context.Context) *IncrementAuthParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the increment auth params
func (o *IncrementAuthParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the increment auth params
func (o *IncrementAuthParams) WithHTTPClient(client *http.Client) *IncrementAuthParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the increment auth params
func (o *IncrementAuthParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the increment auth params
func (o *IncrementAuthParams) WithID(id string) *IncrementAuthParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the increment auth params
func (o *IncrementAuthParams) SetID(id string) {
	o.ID = id
}

// WithIncrementAuthRequest adds the incrementAuthRequest to the increment auth params
func (o *IncrementAuthParams) WithIncrementAuthRequest(incrementAuthRequest IncrementAuthBody) *IncrementAuthParams {
	o.SetIncrementAuthRequest(incrementAuthRequest)
	return o
}

// SetIncrementAuthRequest adds the incrementAuthRequest to the increment auth params
func (o *IncrementAuthParams) SetIncrementAuthRequest(incrementAuthRequest IncrementAuthBody) {
	o.IncrementAuthRequest = incrementAuthRequest
}

// WriteToRequest writes these params to a swagger request
func (o *IncrementAuthParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.IncrementAuthRequest); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
