// Code generated by go-swagger; DO NOT EDIT.

package decision_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateBundledDecisionManagerCaseParams creates a new CreateBundledDecisionManagerCaseParams object
// with the default values initialized.
func NewCreateBundledDecisionManagerCaseParams() *CreateBundledDecisionManagerCaseParams {
	var ()
	return &CreateBundledDecisionManagerCaseParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateBundledDecisionManagerCaseParamsWithTimeout creates a new CreateBundledDecisionManagerCaseParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateBundledDecisionManagerCaseParamsWithTimeout(timeout time.Duration) *CreateBundledDecisionManagerCaseParams {
	var ()
	return &CreateBundledDecisionManagerCaseParams{

		timeout: timeout,
	}
}

// NewCreateBundledDecisionManagerCaseParamsWithContext creates a new CreateBundledDecisionManagerCaseParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateBundledDecisionManagerCaseParamsWithContext(ctx context.Context) *CreateBundledDecisionManagerCaseParams {
	var ()
	return &CreateBundledDecisionManagerCaseParams{

		Context: ctx,
	}
}

// NewCreateBundledDecisionManagerCaseParamsWithHTTPClient creates a new CreateBundledDecisionManagerCaseParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateBundledDecisionManagerCaseParamsWithHTTPClient(client *http.Client) *CreateBundledDecisionManagerCaseParams {
	var ()
	return &CreateBundledDecisionManagerCaseParams{
		HTTPClient: client,
	}
}

/*CreateBundledDecisionManagerCaseParams contains all the parameters to send to the API endpoint
for the create bundled decision manager case operation typically these are written to a http.Request
*/
type CreateBundledDecisionManagerCaseParams struct {

	/*CreateBundledDecisionManagerCaseRequest*/
	CreateBundledDecisionManagerCaseRequest CreateBundledDecisionManagerCaseBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create bundled decision manager case params
func (o *CreateBundledDecisionManagerCaseParams) WithTimeout(timeout time.Duration) *CreateBundledDecisionManagerCaseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create bundled decision manager case params
func (o *CreateBundledDecisionManagerCaseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create bundled decision manager case params
func (o *CreateBundledDecisionManagerCaseParams) WithContext(ctx context.Context) *CreateBundledDecisionManagerCaseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create bundled decision manager case params
func (o *CreateBundledDecisionManagerCaseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create bundled decision manager case params
func (o *CreateBundledDecisionManagerCaseParams) WithHTTPClient(client *http.Client) *CreateBundledDecisionManagerCaseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create bundled decision manager case params
func (o *CreateBundledDecisionManagerCaseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreateBundledDecisionManagerCaseRequest adds the createBundledDecisionManagerCaseRequest to the create bundled decision manager case params
func (o *CreateBundledDecisionManagerCaseParams) WithCreateBundledDecisionManagerCaseRequest(createBundledDecisionManagerCaseRequest CreateBundledDecisionManagerCaseBody) *CreateBundledDecisionManagerCaseParams {
	o.SetCreateBundledDecisionManagerCaseRequest(createBundledDecisionManagerCaseRequest)
	return o
}

// SetCreateBundledDecisionManagerCaseRequest adds the createBundledDecisionManagerCaseRequest to the create bundled decision manager case params
func (o *CreateBundledDecisionManagerCaseParams) SetCreateBundledDecisionManagerCaseRequest(createBundledDecisionManagerCaseRequest CreateBundledDecisionManagerCaseBody) {
	o.CreateBundledDecisionManagerCaseRequest = createBundledDecisionManagerCaseRequest
}

// WriteToRequest writes these params to a swagger request
func (o *CreateBundledDecisionManagerCaseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.CreateBundledDecisionManagerCaseRequest); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
